language: php
os:
  - linux
dist: xenial

git:
    depth: 1

cache:
  directories:
    - $HOME/.composer/cache

jobs:
    include:
        - php: 7.2
        - php: 7.3
        - php: 7.4
        - php: 8.0
        - php: 7.2
          env: COMPOSER_FLAGS='--prefer-lowest --prefer-stable'
    fast_finish: true

before_script:
    - composer self-update
    - composer update $COMPOSER_FLAGS

script:
    - vendor/bin/phpunit
    - php tests/benchmark.php json 3
    - php tests/benchmark.php yml 3
    - php tests/benchmark.php xml 3

after_script:
    - vendor/bin/phpstan

