name: CI

on:
    push:
        branches:
            - 1.x
    pull_request:

jobs:
    lint:
        runs-on: ubuntu-latest
        continue-on-error: true
        strategy:
            matrix:
                php:
                    - "7.4"
                    - "8.0"
                    - "8.1"
                    - "8.2"
                    - "8.3"

        steps:
            -   name: Checkout
                uses: actions/checkout@v3

            -   name: Setup PHP
                uses: shivammathur/setup-php@v2
                with:
                    coverage: "none"
                    extensions: "pdo,sqlite"
                    ini-values: "memory_limit=-1"
                    php-version: "${{ matrix.php }}"
                env:
                    fail-fast: true
                    update: true

            -   name: Setup Composer
                uses: "ramsey/composer-install@v2"
                with:
                    dependency-versions: "${{ matrix.dependencies }}"
                    composer-options: "${{ matrix.composer-options }}"

            -   name: Lint PHP files
                run: vendor/bin/phplint

            -   name: Run PHPStan
                run: vendor/bin/phpstan

    test:
        runs-on: ubuntu-latest
        continue-on-error: true
        strategy:
            matrix:
                php:
                    - "7.4"
                    - "8.0"
                    - "8.1"
                    - "8.2"
                    - "8.3"
                dependencies:
                    - "lowest"
                    - "highest"

        steps:
            -   name: Checkout
                uses: actions/checkout@v3

            -   name: Setup PHP
                uses: shivammathur/setup-php@v2
                with:
                    coverage: "none"
                    extensions: "pdo,sqlite"
                    ini-values: "memory_limit=-1"
                    php-version: "${{ matrix.php }}"
                env:
                    fail-fast: true
                    update: true

            -   name: Setup Composer
                uses: "ramsey/composer-install@v2"
                with:
                    dependency-versions: "${{ matrix.dependencies }}"
                    composer-options: "${{ matrix.composer-options }}"

            -   name: Validate composer.json
                run: composer validate --strict

            -   name: Run tests
                run: vendor/bin/phpunit
